stages:
  - build
  - install
  - test

build:
  stage: build
  script:
    - cd backend && echo "Build step completed"
    - sleep 10

install_dependencies:
  stage: install
  script:
    - cd backend && npm install
    - sleep 10

run_tests:
  stage: test
  script:
    - cd backend && npm test

# security_scan:
#   stage: security
#   script:
#     - cd backend && npm audit --audit-level=high; exit 0